build_android:
  stage: build
  script:
    - ./fetch-keystore.sh && ./build_android.sh
  tags:
    - android
  only:
    - master

deploy_android_alpha:
  stage: deploy
  script:
    - ./fetch-keystore.sh && TARGET=publishRelease ./build_android.sh
  tags:
    - android
  only:
    - android-alpha

#build_ios:
#  stage: build
#   script:
#     - ./build_ios.sh
#   tags:
#     - ios
#   only:
#     - master
#
# deploy_ios_alpha:
#   stage: deploy
#   script:
#     - TARGET=publish ./build_ios.sh
#   tags:
#     - ios
#   only:
#     - ios-alpha
